"use client"

import { useState, useEffect } from "react"
import { Home, X, Copy, Check, Plus } from "lucide-react"
import Image from "next/image"
import { config } from "@/lib/config"

export default function TokenPage() {
  const [copied, setCopied] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  const handleCopy = () => {
    navigator.clipboard.writeText(config.tokenCA)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const faqItems = [
    {
      question: "WHAT HAPPENS WITH CREATOR REWARDS?",
      answer: "100% of all creator rewards generated by $SAFEMOON are automatically used for USDC buybacks via pump.fun Agent Mode. No manual intervention — pure on-chain automation."
    },
    {
      question: "DO I NEED TO STAKE OR CLAIM ANYTHING?",
      answer: "No. The buyback mechanism works automatically. Just hold $SAFEMOON and benefit from constant buy pressure generated by the creator reward reinvestment."
    },
    {
      question: "WHAT IS PUMP.FUN AGENT MODE?",
      answer: "Agent Mode is pump.fun's automated trading system. Our creator rewards are routed directly into it, creating perpetual USDC buybacks that support the token price."
    },
    {
      question: "HOW IS THIS DIFFERENT FROM THE ORIGINAL SAFEMOON?",
      answer: "The true SafeMoon spirit — automated tokenomics that reward holders — but rebuilt on Solana with real transparency. No manual burns, no hidden wallets. 100% creator rewards → buybacks. Now stable on USDC."
    }
  ]

  const flowSteps = [
    {
      number: "01",
      title: "CREATOR REWARDS",
      description: "Every trade of $SAFEMOON generates creator rewards on pump.fun — these accrue automatically with every buy and sell."
    },
    {
      number: "02",
      title: "AGENT MODE",
      description: "100% of creator rewards are routed into pump.fun Agent Mode — an automated on-chain buyback engine. No human required."
    },
    {
      number: "03",
      title: "USDC BUYBACKS",
      description: "Agent Mode executes perpetual USDC buybacks, creating constant buy pressure and supporting the token price for all holders."
    }
  ]

  const marqueeText = "★ 100% CREATOR REWARDS → USDC BUYBACKS ● PUMP.FUN AGENT MODE ● THE TRUE SAFEMOON SPIRIT ● NOW STABLE ON USDC ● NO STAKING REQUIRED ● AUTOMATIC BUYBACKS ● BUILT ON SOLANA ● "

  return (
    <div className="min-h-screen bg-[#060D1F] relative">
      {/* Background image */}
      <div className="fixed inset-0 z-0">
        <Image
          src="/bg-astronaut.jpg"
          alt=""
          fill
          className="object-cover"
          style={{ opacity: 0.25 }}
          priority
        />
      </div>
      {/* Header */}
      <header className="border-b border-white/10 bg-black/30 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-6">
            <a href="/" className="flex items-center gap-2 font-black text-white text-lg tracking-tight">
              <Image
                src="/logo.jpg"
                alt="SafeMoon logo"
                width={32}
                height={32}
                className="border-2 border-black rounded-full"
              />
              SAFEMOON
            </a>
            <nav className="hidden sm:flex items-center gap-1">
              <a href="/" className="flex items-center gap-1.5 px-3 py-1.5 bg-[#2563EB] text-white font-bold text-sm border-2 border-black">
                <Home className="w-4 h-4" />
                HOME
              </a>
            </nav>
          </div>
          {config.twitterUrl && (
            <a
              href={config.twitterUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center w-10 h-10 bg-black text-white hover:bg-[#2563EB] transition-colors"
              aria-label="Follow SafeMoon on X"
            >
              <X className="w-5 h-5" />
            </a>
          )}
        </div>
      </header>

      <main className="relative z-10 max-w-7xl mx-auto px-4 py-6 space-y-6">

        {/* Hero Section */}
        <div className="grid md:grid-cols-[300px_1fr] gap-4">
          {/* Left Card — Full Logo */}
          <div className="bg-[#0a1a3a] border-4 border-black p-6 flex flex-col items-center justify-center min-h-[280px]">
            <Image
              src="/logo.jpg"
              alt="SafeMoon"
              width={200}
              height={200}
              className="rounded-full border-4 border-[#2563EB]"
            />
            <h1 className="text-3xl font-black leading-none text-white mt-4 tracking-tight">
              SAFEMOON
            </h1>
            <div className="inline-flex items-center gap-2 bg-black text-white text-xs font-bold px-2 py-1 mt-3">
              <span className="w-2 h-2 bg-[#3B82F6] rounded-full animate-pulse"></span>
              BUYBACKS ACTIVE
            </div>
          </div>

          {/* Right Card */}
          <div className="bg-[#1D4ED8] border-4 border-black p-8 flex flex-col justify-between">
            <div>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-black text-white leading-none mb-6">
                THE TRUE<br />SAFEMOON<br />SPIRIT
              </h2>
              <p className="text-[#BFDBFE] text-sm max-w-md leading-relaxed">
                100% of creator rewards are used for automatic USDC buybacks via pump.fun Agent Mode. No manual burns, no hidden wallets. Now stable on USDC.
              </p>
            </div>
            <div className="mt-6">
              <a
                href="#"
                className="bg-white text-[#060D1F] font-bold px-8 py-3 border-4 border-black hover:bg-[#BFDBFE] transition-colors"
              >
                BUY NOW →
              </a>
            </div>
          </div>
        </div>

        {/* Buyback Mechanism Section */}
        <div className="grid md:grid-cols-[1fr_1.5fr] gap-4">
          {/* USDC Card */}
          <div className="bg-[#1A3A6E] border-4 border-black p-6">
            <p className="text-xs font-bold text-[#93C5FD] mb-2">BUYBACK TOKEN</p>
            <h3 className="text-5xl md:text-6xl font-black text-white mb-4">
              US<span className="text-[#60A5FA]">DC</span>
            </h3>
            <p className="text-sm text-[#BFDBFE]">
              All creator rewards are converted to USDC buybacks automatically via pump.fun Agent Mode. Constant buy pressure, real dollar value backing every trade.
            </p>
          </div>

          {/* How it works Card */}
          <div className="bg-[#EFF6FF] border-4 border-black p-6">
            <h3 className="text-2xl font-black mb-4 text-[#060D1F]">HOW BUYBACKS WORK</h3>
            <p className="text-sm text-[#1A3A6E] mb-4">
              Every buy and sell of $SAFEMOON generates creator rewards on pump.fun. Instead of pocketing them, 100% is routed into Agent Mode — pump.fun&apos;s automated trading engine — which executes perpetual USDC buybacks. This creates constant buy pressure and supports the token price for all holders.
            </p>
            <button
              onClick={handleCopy}
              className="w-full flex items-center justify-between bg-[#DBEAFE] border-2 border-black p-3 font-mono text-xs hover:bg-[#BFDBFE] transition-colors text-[#060D1F]"
            >
              <span className="truncate">{config.tokenCA || "CA COMING SOON"}</span>
              {copied ? <Check className="w-4 h-4 text-[#2563EB] flex-shrink-0 ml-2" /> : <Copy className="w-4 h-4 flex-shrink-0 ml-2" />}
            </button>
            <p className="text-xs text-[#1A3A6E] mt-1">CONTRACT ADDRESS</p>
          </div>
        </div>

        {/* The Flow Section */}
        <div className="bg-[#0D1F3C] border-4 border-black p-6">
          <h3 className="text-3xl font-black mb-6 border-b-4 border-[#2563EB] pb-4 text-white">THE FLOW</h3>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {flowSteps.map((step) => (
              <div key={step.number} className="border-l-4 border-[#2563EB] pl-4">
                <span className="text-xs font-mono text-[#60A5FA]">{step.number}</span>
                <h4 className="text-lg font-black mb-2 text-white">{step.title}</h4>
                <p className="text-sm text-[#93C5FD]">{step.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ Section */}
        <div className="bg-[#1A3A6E] border-4 border-black p-6">
          <h3 className="text-2xl font-black mb-4 text-white">FAQ READOUT</h3>
          <div className="space-y-2">
            {faqItems.map((item, index) => (
              <div key={index} className="border-b-2 border-[#2563EB] last:border-b-0">
                <button
                  onClick={() => setOpenFaq(openFaq === index ? null : index)}
                  className="w-full flex items-center justify-between py-3 text-left font-bold text-sm text-white hover:text-[#60A5FA] transition-colors"
                >
                  {item.question}
                  <Plus className={`w-5 h-5 flex-shrink-0 ml-2 transition-transform ${openFaq === index ? "rotate-45" : ""}`} />
                </button>
                {openFaq === index && (
                  <p className="pb-3 text-sm text-[#BFDBFE]">{item.answer}</p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Marquee */}
        <div className="bg-[#2563EB] border-4 border-black overflow-hidden">
          <div className="py-3 flex">
            <div className="animate-marquee flex whitespace-nowrap">
              <span className="font-bold text-sm mx-4 text-white">{marqueeText}</span>
              <span className="font-bold text-sm mx-4 text-white">{marqueeText}</span>
            </div>
          </div>
        </div>

        {/* Banner Image */}
        <div className="border-4 border-black overflow-hidden">
          <Image
            src="/banner.jpg"
            alt="SafeMoon on USDC"
            width={1400}
            height={400}
            className="w-full object-cover"
          />
        </div>
      </main>

      {/* Footer */}
      <footer className="relative z-10 bg-[#0D1F3C]/95 backdrop-blur-sm border-t-4 border-black mt-6">
        <div className="max-w-7xl mx-auto px-4 py-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Image
              src="/logo.jpg"
              alt="SafeMoon"
              width={24}
              height={24}
              className="border border-black rounded-full"
            />
            <p className="text-white text-sm font-bold">
              SAFEMOON © 2026 · BUILT ON SOLANA
            </p>
          </div>
          <div className="flex items-center gap-4">
            {config.twitterUrl && (
              <a
                href={config.twitterUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 text-white text-sm font-bold hover:text-[#60A5FA] transition-colors"
              >
                <X className="w-4 h-4" />
                FOLLOW
              </a>
            )}
          </div>
        </div>
      </footer>
    </div>
  )
}
